Project1:对文件diabetes.csv中的数据进行处理，将文件夹pima-diabetes放在E：盘的input文件夹下

In [6]:
from pandas import *
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib notebook
from scipy.stats import mode

import os
print(os.listdir("/home/data/Desktop"))

['4-可视化库Seaborn', 'model.png', '3-可视化库matpltlib', '1-科学计算库numpy', 'diabetes.csv', '.ipynb_checkpoints', '2-数据分析处理库pandas', 'answer1-python-data-pre-processing-handy-tips.ipynb']

In [7]:
################################读入diabetes.csv文件到diabetes################################### 
diabetes = pd.read_csv('/home/data/Desktop/diabetes.csv')
################################读入diabetes.csv文件到diabetes###################################

In [8]:
################################显示diabetes的前5行################################### 
diabetes.head(5)
################################显示diabetes的前5行###################################

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

Check for Summary Statistics

In [9]:
################################显示diabetes的详细信息，包括样本数、均值、方差等等################################## 
diabetes.describe()
################################显示diabetes的详细信息，包括样本数、均值、方差等等##################################

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [10]:
################################显示diabetes中Outcome列中每种值出现的次数################################## 
diabetes["Outcome"].value_counts()
################################显示diabetes中Outcome列中每种值出现的次数##################################

0    500
1    268
Name: Outcome, dtype: int64

### Check missing values

In [11]:
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [12]:
################################显示diabetes中所有列的标题名################################## 
diabetes.columns
################################显示diabetes中所有列的标题名##################################

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [13]:
################################显示diabetes中所有列的值里面为0的个数################################## 
print((diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']] == 0).sum())
################################显示diabetes中所有列的值里面为0的个数##################################

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
dtype: int64

In [14]:
################################将diabetes中所有列的值中为0的值替换为NaN################################## 
diabetes.loc[:,['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI']] = diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI']].replace(0, np.NaN)

################################将diabetes中所有列的值中为0的值替换为NaN################################## 
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,NaN,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [15]:
################################统计diabetes中所有列的值中为null的个数################################## 
diabetes.isnull().sum()
################################统计diabetes中所有列的值中为null的个数##################################

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

## Dealing with missing values

## A. Drop rows having NaN

In [16]:
print("Size before dropping NaN rows",diabetes.shape,"\n")

################################将diabetes中包含NaN的行删掉################################## 
nan_dropped = diabetes.dropna()

################################将diabetes中包含NaN的行删掉################################## 
print(nan_dropped.isnull().sum())
print("\nSize after dropping NaN rows",nan_dropped.shape)

Size before dropping NaN rows (768, 9)

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Size after dropping NaN rows (336, 9)

### **Project2、数据分析的一系列问题**

In [17]:
vector = np.random.chisquare(1,500)
print(vector)
################################打印vector的均值################################## 
print("Mean",np.mean(vector))
################################打印vector的均值################################## 

print("SD",np.std(vector))
print("Range",max(vector)-min(vector))

[3.76861289e+00 4.70824243e-01 1.03327223e-01 5.19432895e-01
 1.49583905e+00 4.61510395e-01 4.69234718e-01 1.30969617e+00
 1.29292360e-01 1.32501760e-01 6.38430721e-01 3.02013130e-01
 2.39566087e-01 6.56596778e-02 1.83084315e-01 9.98899324e-01
 1.18282473e+00 1.43335853e+00 3.55202809e-01 1.94137114e-01
 6.95102688e-01 6.00479545e-02 1.65768589e-02 2.60770986e+00
 1.07816327e+00 1.66092721e-02 1.14219126e+00 2.03566148e+00
 3.59889222e-01 1.59656032e-01 8.37800788e-01 9.82893913e-01
 1.15391215e-01 3.04309000e+00 1.35703801e+00 8.08628469e-02
 4.30374579e+00 7.04319694e-03 5.31149834e-01 3.40469834e-01
 2.27376913e-03 8.05391366e-01 1.60299426e+00 2.50139907e-01
 4.16540561e-02 1.37699671e+00 1.98121219e+00 2.52147817e+00
 1.08666821e+00 1.50084258e-01 1.63891817e+00 1.13820899e+00
 1.52712402e+00 1.87345657e-01 1.57406491e-01 5.35155380e-01
 1.92221223e+00 7.85721545e-06 3.22570881e-02 6.90870772e-01
 6.79887386e-02 3.05870633e+00 1.26836498e-01 1.33995205e-02
 6.42141029e-03 2.83219447e+00 2.07613736e+00 2.79998175e+00
 4.79179233e+00 5.24317822e-02 2.56346664e-03 1.80661173e-02
 7.51164000e-03 8.66332715e-02 2.81729161e-02 1.15214641e+00
 3.77380137e+00 5.49796462e-01 3.41594145e-03 7.90751335e-02
 6.28944687e-01 2.04574917e-01 3.41075752e-01 3.01694273e+00
 4.92338040e-01 2.27925089e-02 4.01147872e-01 4.96736305e-01
 1.19411945e-01 4.61539769e-02 7.00368461e-02 2.92173880e-01
 2.49923528e+00 5.79287749e-02 5.56601944e-03 9.32289078e-01
 1.57944973e+00 2.01383197e-01 1.53079066e-01 3.24742465e+00
 1.41431794e+00 7.20009518e-02 1.45308513e+00 1.18290667e+00
 1.66026932e-01 5.25305310e-01 5.73808715e-01 9.28212130e-01
 3.15655885e+00 1.16247652e-02 1.99594669e-01 4.57699815e-01
 2.16048353e+00 7.23393786e-02 9.50902042e-02 8.41517234e-02
 6.14433224e-04 1.67195060e-01 3.61573554e+00 3.65391071e-02
 1.34034102e+00 8.52106717e-01 1.85901006e-01 1.38236173e-01
 2.52650836e+00 2.41591273e-01 2.04435957e-02 3.56106606e+00
 2.40443816e+00 1.87258757e-02 9.19201760e-01 6.19282165e-02
 3.52971695e+00 2.68775236e-01 5.53926935e-01 3.12162934e+00
 6.18037046e-03 1.22838354e+00 1.91354925e-02 7.52877605e+00
 9.69725107e+00 3.96486203e-01 5.45475335e-01 1.68459116e-01
 2.29476120e+00 2.08691934e+00 1.28217478e+00 1.39856354e-03
 2.89904128e-01 1.72677647e-03 2.17234082e-02 9.15298012e-02
 4.92874542e-01 6.42180357e-01 5.60195782e-01 5.13005462e-01
 3.65515620e-01 1.38703857e+00 4.47478721e-03 7.49325208e-01
 1.69835000e+00 6.48269925e-01 7.58472073e-03 5.13930835e-03
 7.33847797e-02 4.51778656e-01 1.00916893e-01 1.02340554e+00
 1.23877129e-02 7.73750864e-02 7.48178079e-01 3.46835733e-02
 2.10233244e+00 7.47658354e-01 4.26274838e-02 2.24843415e+00
 1.72170645e-01 8.21316524e-01 3.68510777e+00 4.29468516e-01
 5.00328069e-01 1.68396512e+00 1.13652478e+00 1.59176663e+00
 3.83240340e+00 7.40169944e-02 1.26967437e+00 7.72871026e-01
 1.96405915e+00 5.61691385e-01 3.49039015e-02 1.43393816e+00
 1.60784273e+00 6.19092693e-01 7.70590681e-01 1.91819919e-02
 1.91720074e+00 9.14768297e-01 6.10919818e-04 7.11488963e-04
 8.71813860e-02 2.22043893e+00 6.78560814e-01 9.20122643e-01
 2.50243256e+00 1.32445403e-01 1.18825029e+00 5.73743468e-01
 7.38694053e-01 6.73687195e-01 1.09942041e+00 9.00739722e-02
 6.52120156e-01 2.68665958e+00 1.40944795e+00 1.28907086e+00
 1.58500071e-02 7.73639764e-01 3.98768817e-02 1.28955441e-01
 4.98742935e-01 1.81923665e+00 7.15827483e+00 1.65606354e+00
 7.38155521e+00 1.45838899e+00 1.69133095e-03 4.43201096e+00
 5.30369167e+00 9.48665147e-02 7.96877141e-02 1.77770409e+00
 6.42786483e-01 8.03875654e-01 2.52494745e+00 2.96409122e+00
 6.39946842e-01 9.09563306e-01 3.22479090e+00 1.43768468e-01
 1.19016213e+00 1.74425162e+00 4.45756972e-03 1.55811103e-01
 2.38130379e-01 1.54234602e+00 2.42578228e+00 3.25253825e+00
 7.76285298e-01 2.11886472e-01 5.40664096e-01 5.24104243e-01
 1.18538411e+00 2.26278901e-01 5.86648570e-01 1.07548848e-02
 9.97274984e-02 1.03553518e-01 2.63930566e-01 2.03911696e-01
 5.98611718e-01 1.00270182e+00 1.91355490e+00 1.39229087e+00
 1.99170579e-01 1.29683646e+00 1.48753029e+00 1.50274533e+00
 3.18643407e-02 5.87384130e-02 1.55457251e-01 1.27600924e-01
 6.90090621e+00 6.74012582e-05 1.30075946e-02 1.49924111e-01
 6.75090529e-03 8.98998256e-01 2.26807636e+00 1.01929902e-03
 4.20172852e-02 9.49290547e-01 1.99580986e-01 4.55827854e-05
 1.70466908e-03 1.00548815e+00 1.07524683e+00 6.12874193e-01
 1.74599716e+00 2.93295290e-02 8.39801848e-01 5.49935902e+00
 1.98913214e+00 2.25847111e-01 1.25336101e+00 8.69432938e-01
 1.01563841e+00 1.49770114e-05 4.97137412e-01 2.10426741e+00
 1.14300265e-02 3.93697182e-01 3.01862095e+00 2.63169381e+00
 3.87445097e-01 9.78137501e-02 3.16141794e-01 4.88074726e-02
 2.46194613e+00 2.20450333e+00 8.83424932e-01 6.72479284e-01
 1.13740946e+00 1.65364189e-03 2.00753436e-02 1.13995458e-02
 7.82598150e-01 4.47457865e+00 1.14434945e+00 2.86137087e-01
 2.94228939e+00 5.50463865e-01 2.53841278e-01 1.94807050e-01
 8.98382994e-04 1.15678444e+00 3.62067736e-01 1.61513698e-02
 7.48228000e-02 9.99323513e-01 1.51060697e-02 3.69026773e+00
 3.93520232e-01 1.09713756e+00 6.40443742e-01 1.11313152e+00
 8.77665906e-01 1.45349535e-01 5.78128767e+00 1.62133248e+00
 3.30903306e-01 2.07927011e-02 2.96543246e+00 9.26301845e-01
 4.14040436e-01 3.08905271e+00 6.48888996e-01 1.39812575e+00
 1.18906501e+00 2.39663511e-02 1.88036971e-01 1.68734199e-01
 2.37089573e-01 4.15699428e+00 1.84187630e-01 1.07424966e+00
 2.82633727e-01 4.28573922e-01 9.19884411e-02 1.81877766e+00
 1.71754948e+00 2.51302316e+00 1.06388215e-01 1.72471414e-01
 1.05314483e+00 7.54561228e-01 1.29749348e+00 1.67725541e-01
 9.95306408e-01 2.55452564e+00 2.71370986e-01 7.85888907e-01
 5.08578206e-01 8.50481027e-01 2.71360629e+00 1.29833886e+00
 1.45899815e+00 1.89461413e-01 1.57980119e-02 7.24419460e-01
 5.50506008e-01 1.26276985e-01 1.32450007e+00 3.21435784e-01
 1.91857021e-01 2.17894278e-01 1.63275861e+00 1.63184620e+00
 9.91971096e-01 2.32404285e+00 3.54037201e-01 4.06175152e+00
 3.38866303e+00 3.18988592e-01 4.28799454e+00 1.49015005e+00
 4.09878046e-01 6.43611501e-02 4.08024006e-01 1.16483204e+00
 8.56244989e-01 1.08521731e+00 1.57314151e+00 2.69977709e+00
 7.37014005e-02 1.87304108e-01 3.86054193e+00 6.63736913e-03
 2.75715403e+00 4.84998006e-01 4.06850770e-03 3.18515652e+00
 5.15081572e-01 1.67065424e-01 1.34650661e+00 4.40665994e+00
 3.67532167e-02 1.67374322e-03 2.56602837e+00 3.38549394e+00
 6.82448373e+00 1.18914175e+00 2.71568487e+00 7.34464637e-01
 5.64158368e-02 1.19100586e+00 1.42098967e+00 1.96187371e+00
 6.82309395e+00 1.05516305e+00 4.18669920e+00 1.38703754e+00
 3.00031518e-03 2.18694755e+00 5.65502015e-01 9.72278104e-01
 1.33287556e-01 8.17759258e-02 4.52922755e-01 1.65490263e-01
 1.30331046e-01 3.63261428e-01 6.04444017e-01 7.33052561e-01
 1.02794900e-01 2.18071297e-02 2.65412880e-01 7.29099045e-01
 4.61285701e-01 3.17591898e-01 2.98809423e-01 7.74056708e-02
 1.58361892e+00 1.08515950e-01 7.06117602e+00 4.66398149e-01
 2.89039126e+00 5.66371336e-01 8.59797888e-01 2.12436154e-02
 1.62953609e+00 2.01996810e-01 4.12081273e+00 4.49806343e-01
 1.29116833e+00 2.28964749e-02 1.48014532e+00 1.74194658e-01
 7.60258243e-01 7.18838545e+00 1.62719298e+00 1.52478609e-02
 1.91943440e-01 4.22273199e-01 1.88127703e-01 1.91847487e-01
 3.00771272e-02 1.66234517e-01 9.78818797e-01 1.81331308e-01
 5.33304009e-01 4.94031402e-01 4.06021762e+00 1.68935335e-01
 6.43668695e-01 4.02864071e+00 3.18497875e-01 5.01843335e-01
 9.14485022e-01 6.94541653e-01 5.83523129e-01 2.67306614e-03
 1.27779869e+00 4.84787722e+00 1.94360765e+00 1.00065937e+00
 9.99590362e-04 1.31141693e-01 1.60270084e+00 4.20743513e-01]
Mean 1.0832312232062964
SD 1.4067529409921113
Range 9.697243209423094

### Reshape

In [18]:
vector.shape

(500,)

In [19]:
################################将一维向量vector转成大小为500*1的二维向量并赋值给row_vector################################## 
row_vector = vector.reshape(-1,1)
################################将一维向量vector转成大小为500*1的二维向量并赋值给row_vector################################## 
row_vector.shape
print(row_vector)

[[3.76861289e+00]
 [4.70824243e-01]
 [1.03327223e-01]
 [5.19432895e-01]
 [1.49583905e+00]
 [4.61510395e-01]
 [4.69234718e-01]
 [1.30969617e+00]
 [1.29292360e-01]
 [1.32501760e-01]
 [6.38430721e-01]
 [3.02013130e-01]
 [2.39566087e-01]
 [6.56596778e-02]
 [1.83084315e-01]
 [9.98899324e-01]
 [1.18282473e+00]
 [1.43335853e+00]
 [3.55202809e-01]
 [1.94137114e-01]
 [6.95102688e-01]
 [6.00479545e-02]
 [1.65768589e-02]
 [2.60770986e+00]
 [1.07816327e+00]
 [1.66092721e-02]
 [1.14219126e+00]
 [2.03566148e+00]
 [3.59889222e-01]
 [1.59656032e-01]
 [8.37800788e-01]
 [9.82893913e-01]
 [1.15391215e-01]
 [3.04309000e+00]
 [1.35703801e+00]
 [8.08628469e-02]
 [4.30374579e+00]
 [7.04319694e-03]
 [5.31149834e-01]
 [3.40469834e-01]
 [2.27376913e-03]
 [8.05391366e-01]
 [1.60299426e+00]
 [2.50139907e-01]
 [4.16540561e-02]
 [1.37699671e+00]
 [1.98121219e+00]
 [2.52147817e+00]
 [1.08666821e+00]
 [1.50084258e-01]
 [1.63891817e+00]
 [1.13820899e+00]
 [1.52712402e+00]
 [1.87345657e-01]
 [1.57406491e-01]
 [5.35155380e-01]
 [1.92221223e+00]
 [7.85721545e-06]
 [3.22570881e-02]
 [6.90870772e-01]
 [6.79887386e-02]
 [3.05870633e+00]
 [1.26836498e-01]
 [1.33995205e-02]
 [6.42141029e-03]
 [2.83219447e+00]
 [2.07613736e+00]
 [2.79998175e+00]
 [4.79179233e+00]
 [5.24317822e-02]
 [2.56346664e-03]
 [1.80661173e-02]
 [7.51164000e-03]
 [8.66332715e-02]
 [2.81729161e-02]
 [1.15214641e+00]
 [3.77380137e+00]
 [5.49796462e-01]
 [3.41594145e-03]
 [7.90751335e-02]
 [6.28944687e-01]
 [2.04574917e-01]
 [3.41075752e-01]
 [3.01694273e+00]
 [4.92338040e-01]
 [2.27925089e-02]
 [4.01147872e-01]
 [4.96736305e-01]
 [1.19411945e-01]
 [4.61539769e-02]
 [7.00368461e-02]
 [2.92173880e-01]
 [2.49923528e+00]
 [5.79287749e-02]
 [5.56601944e-03]
 [9.32289078e-01]
 [1.57944973e+00]
 [2.01383197e-01]
 [1.53079066e-01]
 [3.24742465e+00]
 [1.41431794e+00]
 [7.20009518e-02]
 [1.45308513e+00]
 [1.18290667e+00]
 [1.66026932e-01]
 [5.25305310e-01]
 [5.73808715e-01]
 [9.28212130e-01]
 [3.15655885e+00]
 [1.16247652e-02]
 [1.99594669e-01]
 [4.57699815e-01]
 [2.16048353e+00]
 [7.23393786e-02]
 [9.50902042e-02]
 [8.41517234e-02]
 [6.14433224e-04]
 [1.67195060e-01]
 [3.61573554e+00]
 [3.65391071e-02]
 [1.34034102e+00]
 [8.52106717e-01]
 [1.85901006e-01]
 [1.38236173e-01]
 [2.52650836e+00]
 [2.41591273e-01]
 [2.04435957e-02]
 [3.56106606e+00]
 [2.40443816e+00]
 [1.87258757e-02]
 [9.19201760e-01]
 [6.19282165e-02]
 [3.52971695e+00]
 [2.68775236e-01]
 [5.53926935e-01]
 [3.12162934e+00]
 [6.18037046e-03]
 [1.22838354e+00]
 [1.91354925e-02]
 [7.52877605e+00]
 [9.69725107e+00]
 [3.96486203e-01]
 [5.45475335e-01]
 [1.68459116e-01]
 [2.29476120e+00]
 [2.08691934e+00]
 [1.28217478e+00]
 [1.39856354e-03]
 [2.89904128e-01]
 [1.72677647e-03]
 [2.17234082e-02]
 [9.15298012e-02]
 [4.92874542e-01]
 [6.42180357e-01]
 [5.60195782e-01]
 [5.13005462e-01]
 [3.65515620e-01]
 [1.38703857e+00]
 [4.47478721e-03]
 [7.49325208e-01]
 [1.69835000e+00]
 [6.48269925e-01]
 [7.58472073e-03]
 [5.13930835e-03]
 [7.33847797e-02]
 [4.51778656e-01]
 [1.00916893e-01]
 [1.02340554e+00]
 [1.23877129e-02]
 [7.73750864e-02]
 [7.48178079e-01]
 [3.46835733e-02]
 [2.10233244e+00]
 [7.47658354e-01]
 [4.26274838e-02]
 [2.24843415e+00]
 [1.72170645e-01]
 [8.21316524e-01]
 [3.68510777e+00]
 [4.29468516e-01]
 [5.00328069e-01]
 [1.68396512e+00]
 [1.13652478e+00]
 [1.59176663e+00]
 [3.83240340e+00]
 [7.40169944e-02]
 [1.26967437e+00]
 [7.72871026e-01]
 [1.96405915e+00]
 [5.61691385e-01]
 [3.49039015e-02]
 [1.43393816e+00]
 [1.60784273e+00]
 [6.19092693e-01]
 [7.70590681e-01]
 [1.91819919e-02]
 [1.91720074e+00]
 [9.14768297e-01]
 [6.10919818e-04]
 [7.11488963e-04]
 [8.71813860e-02]
 [2.22043893e+00]
 [6.78560814e-01]
 [9.20122643e-01]
 [2.50243256e+00]
 [1.32445403e-01]
 [1.18825029e+00]
 [5.73743468e-01]
 [7.38694053e-01]
 [6.73687195e-01]
 [1.09942041e+00]
 [9.00739722e-02]
 [6.52120156e-01]
 [2.68665958e+00]
 [1.40944795e+00]
 [1.28907086e+00]
 [1.58500071e-02]
 [7.73639764e-01]
 [3.98768817e-02]
 [1.28955441e-01]
 [4.98742935e-01]
 [1.81923665e+00]
 [7.15827483e+00]
 [1.65606354e+00]
 [7.38155521e+00]
 [1.45838899e+00]
 [1.69133095e-03]
 [4.43201096e+00]
 [5.30369167e+00]
 [9.48665147e-02]
 [7.96877141e-02]
 [1.77770409e+00]
 [6.42786483e-01]
 [8.03875654e-01]
 [2.52494745e+00]
 [2.96409122e+00]
 [6.39946842e-01]
 [9.09563306e-01]
 [3.22479090e+00]
 [1.43768468e-01]
 [1.19016213e+00]
 [1.74425162e+00]
 [4.45756972e-03]
 [1.55811103e-01]
 [2.38130379e-01]
 [1.54234602e+00]
 [2.42578228e+00]
 [3.25253825e+00]
 [7.76285298e-01]
 [2.11886472e-01]
 [5.40664096e-01]
 [5.24104243e-01]
 [1.18538411e+00]
 [2.26278901e-01]
 [5.86648570e-01]
 [1.07548848e-02]
 [9.97274984e-02]
 [1.03553518e-01]
 [2.63930566e-01]
 [2.03911696e-01]
 [5.98611718e-01]
 [1.00270182e+00]
 [1.91355490e+00]
 [1.39229087e+00]
 [1.99170579e-01]
 [1.29683646e+00]
 [1.48753029e+00]
 [1.50274533e+00]
 [3.18643407e-02]
 [5.87384130e-02]
 [1.55457251e-01]
 [1.27600924e-01]
 [6.90090621e+00]
 [6.74012582e-05]
 [1.30075946e-02]
 [1.49924111e-01]
 [6.75090529e-03]
 [8.98998256e-01]
 [2.26807636e+00]
 [1.01929902e-03]
 [4.20172852e-02]
 [9.49290547e-01]
 [1.99580986e-01]
 [4.55827854e-05]
 [1.70466908e-03]
 [1.00548815e+00]
 [1.07524683e+00]
 [6.12874193e-01]
 [1.74599716e+00]
 [2.93295290e-02]
 [8.39801848e-01]
 [5.49935902e+00]
 [1.98913214e+00]
 [2.25847111e-01]
 [1.25336101e+00]
 [8.69432938e-01]
 [1.01563841e+00]
 [1.49770114e-05]
 [4.97137412e-01]
 [2.10426741e+00]
 [1.14300265e-02]
 [3.93697182e-01]
 [3.01862095e+00]
 [2.63169381e+00]
 [3.87445097e-01]
 [9.78137501e-02]
 [3.16141794e-01]
 [4.88074726e-02]
 [2.46194613e+00]
 [2.20450333e+00]
 [8.83424932e-01]
 [6.72479284e-01]
 [1.13740946e+00]
 [1.65364189e-03]
 [2.00753436e-02]
 [1.13995458e-02]
 [7.82598150e-01]
 [4.47457865e+00]
 [1.14434945e+00]
 [2.86137087e-01]
 [2.94228939e+00]
 [5.50463865e-01]
 [2.53841278e-01]
 [1.94807050e-01]
 [8.98382994e-04]
 [1.15678444e+00]
 [3.62067736e-01]
 [1.61513698e-02]
 [7.48228000e-02]
 [9.99323513e-01]
 [1.51060697e-02]
 [3.69026773e+00]
 [3.93520232e-01]
 [1.09713756e+00]
 [6.40443742e-01]
 [1.11313152e+00]
 [8.77665906e-01]
 [1.45349535e-01]
 [5.78128767e+00]
 [1.62133248e+00]
 [3.30903306e-01]
 [2.07927011e-02]
 [2.96543246e+00]
 [9.26301845e-01]
 [4.14040436e-01]
 [3.08905271e+00]
 [6.48888996e-01]
 [1.39812575e+00]
 [1.18906501e+00]
 [2.39663511e-02]
 [1.88036971e-01]
 [1.68734199e-01]
 [2.37089573e-01]
 [4.15699428e+00]
 [1.84187630e-01]
 [1.07424966e+00]
 [2.82633727e-01]
 [4.28573922e-01]
 [9.19884411e-02]
 [1.81877766e+00]
 [1.71754948e+00]
 [2.51302316e+00]
 [1.06388215e-01]
 [1.72471414e-01]
 [1.05314483e+00]
 [7.54561228e-01]
 [1.29749348e+00]
 [1.67725541e-01]
 [9.95306408e-01]
 [2.55452564e+00]
 [2.71370986e-01]
 [7.85888907e-01]
 [5.08578206e-01]
 [8.50481027e-01]
 [2.71360629e+00]
 [1.29833886e+00]
 [1.45899815e+00]
 [1.89461413e-01]
 [1.57980119e-02]
 [7.24419460e-01]
 [5.50506008e-01]
 [1.26276985e-01]
 [1.32450007e+00]
 [3.21435784e-01]
 [1.91857021e-01]
 [2.17894278e-01]
 [1.63275861e+00]
 [1.63184620e+00]
 [9.91971096e-01]
 [2.32404285e+00]
 [3.54037201e-01]
 [4.06175152e+00]
 [3.38866303e+00]
 [3.18988592e-01]
 [4.28799454e+00]
 [1.49015005e+00]
 [4.09878046e-01]
 [6.43611501e-02]
 [4.08024006e-01]
 [1.16483204e+00]
 [8.56244989e-01]
 [1.08521731e+00]
 [1.57314151e+00]
 [2.69977709e+00]
 [7.37014005e-02]
 [1.87304108e-01]
 [3.86054193e+00]
 [6.63736913e-03]
 [2.75715403e+00]
 [4.84998006e-01]
 [4.06850770e-03]
 [3.18515652e+00]
 [5.15081572e-01]
 [1.67065424e-01]
 [1.34650661e+00]
 [4.40665994e+00]
 [3.67532167e-02]
 [1.67374322e-03]
 [2.56602837e+00]
 [3.38549394e+00]
 [6.82448373e+00]
 [1.18914175e+00]
 [2.71568487e+00]
 [7.34464637e-01]
 [5.64158368e-02]
 [1.19100586e+00]
 [1.42098967e+00]
 [1.96187371e+00]
 [6.82309395e+00]
 [1.05516305e+00]
 [4.18669920e+00]
 [1.38703754e+00]
 [3.00031518e-03]
 [2.18694755e+00]
 [5.65502015e-01]
 [9.72278104e-01]
 [1.33287556e-01]
 [8.17759258e-02]
 [4.52922755e-01]
 [1.65490263e-01]
 [1.30331046e-01]
 [3.63261428e-01]
 [6.04444017e-01]
 [7.33052561e-01]
 [1.02794900e-01]
 [2.18071297e-02]
 [2.65412880e-01]
 [7.29099045e-01]
 [4.61285701e-01]
 [3.17591898e-01]
 [2.98809423e-01]
 [7.74056708e-02]
 [1.58361892e+00]
 [1.08515950e-01]
 [7.06117602e+00]
 [4.66398149e-01]
 [2.89039126e+00]
 [5.66371336e-01]
 [8.59797888e-01]
 [2.12436154e-02]
 [1.62953609e+00]
 [2.01996810e-01]
 [4.12081273e+00]
 [4.49806343e-01]
 [1.29116833e+00]
 [2.28964749e-02]
 [1.48014532e+00]
 [1.74194658e-01]
 [7.60258243e-01]
 [7.18838545e+00]
 [1.62719298e+00]
 [1.52478609e-02]
 [1.91943440e-01]
 [4.22273199e-01]
 [1.88127703e-01]
 [1.91847487e-01]
 [3.00771272e-02]
 [1.66234517e-01]
 [9.78818797e-01]
 [1.81331308e-01]
 [5.33304009e-01]
 [4.94031402e-01]
 [4.06021762e+00]
 [1.68935335e-01]
 [6.43668695e-01]
 [4.02864071e+00]
 [3.18497875e-01]
 [5.01843335e-01]
 [9.14485022e-01]
 [6.94541653e-01]
 [5.83523129e-01]
 [2.67306614e-03]
 [1.27779869e+00]
 [4.84787722e+00]
 [1.94360765e+00]
 [1.00065937e+00]
 [9.99590362e-04]
 [1.31141693e-01]
 [1.60270084e+00]
 [4.20743513e-01]]

In [20]:
col_vector = vector.reshape(1,-1)
col_vector.shape

(1, 500)

In [21]:
################################将一维向量vector转成大小为10*50的二维向量并赋值给maxtrix################################## 
matrix = vector.reshape(10,50)
################################将一维向量vector转成大小为10*50的二维向量并赋值给maxtrix################################## 
matrix.shape
print(matrix)

[[3.76861289e+00 4.70824243e-01 1.03327223e-01 5.19432895e-01
  1.49583905e+00 4.61510395e-01 4.69234718e-01 1.30969617e+00
  1.29292360e-01 1.32501760e-01 6.38430721e-01 3.02013130e-01
  2.39566087e-01 6.56596778e-02 1.83084315e-01 9.98899324e-01
  1.18282473e+00 1.43335853e+00 3.55202809e-01 1.94137114e-01
  6.95102688e-01 6.00479545e-02 1.65768589e-02 2.60770986e+00
  1.07816327e+00 1.66092721e-02 1.14219126e+00 2.03566148e+00
  3.59889222e-01 1.59656032e-01 8.37800788e-01 9.82893913e-01
  1.15391215e-01 3.04309000e+00 1.35703801e+00 8.08628469e-02
  4.30374579e+00 7.04319694e-03 5.31149834e-01 3.40469834e-01
  2.27376913e-03 8.05391366e-01 1.60299426e+00 2.50139907e-01
  4.16540561e-02 1.37699671e+00 1.98121219e+00 2.52147817e+00
  1.08666821e+00 1.50084258e-01]
 [1.63891817e+00 1.13820899e+00 1.52712402e+00 1.87345657e-01
  1.57406491e-01 5.35155380e-01 1.92221223e+00 7.85721545e-06
  3.22570881e-02 6.90870772e-01 6.79887386e-02 3.05870633e+00
  1.26836498e-01 1.33995205e-02 6.42141029e-03 2.83219447e+00
  2.07613736e+00 2.79998175e+00 4.79179233e+00 5.24317822e-02
  2.56346664e-03 1.80661173e-02 7.51164000e-03 8.66332715e-02
  2.81729161e-02 1.15214641e+00 3.77380137e+00 5.49796462e-01
  3.41594145e-03 7.90751335e-02 6.28944687e-01 2.04574917e-01
  3.41075752e-01 3.01694273e+00 4.92338040e-01 2.27925089e-02
  4.01147872e-01 4.96736305e-01 1.19411945e-01 4.61539769e-02
  7.00368461e-02 2.92173880e-01 2.49923528e+00 5.79287749e-02
  5.56601944e-03 9.32289078e-01 1.57944973e+00 2.01383197e-01
  1.53079066e-01 3.24742465e+00]
 [1.41431794e+00 7.20009518e-02 1.45308513e+00 1.18290667e+00
  1.66026932e-01 5.25305310e-01 5.73808715e-01 9.28212130e-01
  3.15655885e+00 1.16247652e-02 1.99594669e-01 4.57699815e-01
  2.16048353e+00 7.23393786e-02 9.50902042e-02 8.41517234e-02
  6.14433224e-04 1.67195060e-01 3.61573554e+00 3.65391071e-02
  1.34034102e+00 8.52106717e-01 1.85901006e-01 1.38236173e-01
  2.52650836e+00 2.41591273e-01 2.04435957e-02 3.56106606e+00
  2.40443816e+00 1.87258757e-02 9.19201760e-01 6.19282165e-02
  3.52971695e+00 2.68775236e-01 5.53926935e-01 3.12162934e+00
  6.18037046e-03 1.22838354e+00 1.91354925e-02 7.52877605e+00
  9.69725107e+00 3.96486203e-01 5.45475335e-01 1.68459116e-01
  2.29476120e+00 2.08691934e+00 1.28217478e+00 1.39856354e-03
  2.89904128e-01 1.72677647e-03]
 [2.17234082e-02 9.15298012e-02 4.92874542e-01 6.42180357e-01
  5.60195782e-01 5.13005462e-01 3.65515620e-01 1.38703857e+00
  4.47478721e-03 7.49325208e-01 1.69835000e+00 6.48269925e-01
  7.58472073e-03 5.13930835e-03 7.33847797e-02 4.51778656e-01
  1.00916893e-01 1.02340554e+00 1.23877129e-02 7.73750864e-02
  7.48178079e-01 3.46835733e-02 2.10233244e+00 7.47658354e-01
  4.26274838e-02 2.24843415e+00 1.72170645e-01 8.21316524e-01
  3.68510777e+00 4.29468516e-01 5.00328069e-01 1.68396512e+00
  1.13652478e+00 1.59176663e+00 3.83240340e+00 7.40169944e-02
  1.26967437e+00 7.72871026e-01 1.96405915e+00 5.61691385e-01
  3.49039015e-02 1.43393816e+00 1.60784273e+00 6.19092693e-01
  7.70590681e-01 1.91819919e-02 1.91720074e+00 9.14768297e-01
  6.10919818e-04 7.11488963e-04]
 [8.71813860e-02 2.22043893e+00 6.78560814e-01 9.20122643e-01
  2.50243256e+00 1.32445403e-01 1.18825029e+00 5.73743468e-01
  7.38694053e-01 6.73687195e-01 1.09942041e+00 9.00739722e-02
  6.52120156e-01 2.68665958e+00 1.40944795e+00 1.28907086e+00
  1.58500071e-02 7.73639764e-01 3.98768817e-02 1.28955441e-01
  4.98742935e-01 1.81923665e+00 7.15827483e+00 1.65606354e+00
  7.38155521e+00 1.45838899e+00 1.69133095e-03 4.43201096e+00
  5.30369167e+00 9.48665147e-02 7.96877141e-02 1.77770409e+00
  6.42786483e-01 8.03875654e-01 2.52494745e+00 2.96409122e+00
  6.39946842e-01 9.09563306e-01 3.22479090e+00 1.43768468e-01
  1.19016213e+00 1.74425162e+00 4.45756972e-03 1.55811103e-01
  2.38130379e-01 1.54234602e+00 2.42578228e+00 3.25253825e+00
  7.76285298e-01 2.11886472e-01]
 [5.40664096e-01 5.24104243e-01 1.18538411e+00 2.26278901e-01
  5.86648570e-01 1.07548848e-02 9.97274984e-02 1.03553518e-01
  2.63930566e-01 2.03911696e-01 5.98611718e-01 1.00270182e+00
  1.91355490e+00 1.39229087e+00 1.99170579e-01 1.29683646e+00
  1.48753029e+00 1.50274533e+00 3.18643407e-02 5.87384130e-02
  1.55457251e-01 1.27600924e-01 6.90090621e+00 6.74012582e-05
  1.30075946e-02 1.49924111e-01 6.75090529e-03 8.98998256e-01
  2.26807636e+00 1.01929902e-03 4.20172852e-02 9.49290547e-01
  1.99580986e-01 4.55827854e-05 1.70466908e-03 1.00548815e+00
  1.07524683e+00 6.12874193e-01 1.74599716e+00 2.93295290e-02
  8.39801848e-01 5.49935902e+00 1.98913214e+00 2.25847111e-01
  1.25336101e+00 8.69432938e-01 1.01563841e+00 1.49770114e-05
  4.97137412e-01 2.10426741e+00]
 [1.14300265e-02 3.93697182e-01 3.01862095e+00 2.63169381e+00
  3.87445097e-01 9.78137501e-02 3.16141794e-01 4.88074726e-02
  2.46194613e+00 2.20450333e+00 8.83424932e-01 6.72479284e-01
  1.13740946e+00 1.65364189e-03 2.00753436e-02 1.13995458e-02
  7.82598150e-01 4.47457865e+00 1.14434945e+00 2.86137087e-01
  2.94228939e+00 5.50463865e-01 2.53841278e-01 1.94807050e-01
  8.98382994e-04 1.15678444e+00 3.62067736e-01 1.61513698e-02
  7.48228000e-02 9.99323513e-01 1.51060697e-02 3.69026773e+00
  3.93520232e-01 1.09713756e+00 6.40443742e-01 1.11313152e+00
  8.77665906e-01 1.45349535e-01 5.78128767e+00 1.62133248e+00
  3.30903306e-01 2.07927011e-02 2.96543246e+00 9.26301845e-01
  4.14040436e-01 3.08905271e+00 6.48888996e-01 1.39812575e+00
  1.18906501e+00 2.39663511e-02]
 [1.88036971e-01 1.68734199e-01 2.37089573e-01 4.15699428e+00
  1.84187630e-01 1.07424966e+00 2.82633727e-01 4.28573922e-01
  9.19884411e-02 1.81877766e+00 1.71754948e+00 2.51302316e+00
  1.06388215e-01 1.72471414e-01 1.05314483e+00 7.54561228e-01
  1.29749348e+00 1.67725541e-01 9.95306408e-01 2.55452564e+00
  2.71370986e-01 7.85888907e-01 5.08578206e-01 8.50481027e-01
  2.71360629e+00 1.29833886e+00 1.45899815e+00 1.89461413e-01
  1.57980119e-02 7.24419460e-01 5.50506008e-01 1.26276985e-01
  1.32450007e+00 3.21435784e-01 1.91857021e-01 2.17894278e-01
  1.63275861e+00 1.63184620e+00 9.91971096e-01 2.32404285e+00
  3.54037201e-01 4.06175152e+00 3.38866303e+00 3.18988592e-01
  4.28799454e+00 1.49015005e+00 4.09878046e-01 6.43611501e-02
  4.08024006e-01 1.16483204e+00]
 [8.56244989e-01 1.08521731e+00 1.57314151e+00 2.69977709e+00
  7.37014005e-02 1.87304108e-01 3.86054193e+00 6.63736913e-03
  2.75715403e+00 4.84998006e-01 4.06850770e-03 3.18515652e+00
  5.15081572e-01 1.67065424e-01 1.34650661e+00 4.40665994e+00
  3.67532167e-02 1.67374322e-03 2.56602837e+00 3.38549394e+00
  6.82448373e+00 1.18914175e+00 2.71568487e+00 7.34464637e-01
  5.64158368e-02 1.19100586e+00 1.42098967e+00 1.96187371e+00
  6.82309395e+00 1.05516305e+00 4.18669920e+00 1.38703754e+00
  3.00031518e-03 2.18694755e+00 5.65502015e-01 9.72278104e-01
  1.33287556e-01 8.17759258e-02 4.52922755e-01 1.65490263e-01
  1.30331046e-01 3.63261428e-01 6.04444017e-01 7.33052561e-01
  1.02794900e-01 2.18071297e-02 2.65412880e-01 7.29099045e-01
  4.61285701e-01 3.17591898e-01]
 [2.98809423e-01 7.74056708e-02 1.58361892e+00 1.08515950e-01
  7.06117602e+00 4.66398149e-01 2.89039126e+00 5.66371336e-01
  8.59797888e-01 2.12436154e-02 1.62953609e+00 2.01996810e-01
  4.12081273e+00 4.49806343e-01 1.29116833e+00 2.28964749e-02
  1.48014532e+00 1.74194658e-01 7.60258243e-01 7.18838545e+00
  1.62719298e+00 1.52478609e-02 1.91943440e-01 4.22273199e-01
  1.88127703e-01 1.91847487e-01 3.00771272e-02 1.66234517e-01
  9.78818797e-01 1.81331308e-01 5.33304009e-01 4.94031402e-01
  4.06021762e+00 1.68935335e-01 6.43668695e-01 4.02864071e+00
  3.18497875e-01 5.01843335e-01 9.14485022e-01 6.94541653e-01
  5.83523129e-01 2.67306614e-03 1.27779869e+00 4.84787722e+00
  1.94360765e+00 1.00065937e+00 9.99590362e-04 1.31141693e-01
  1.60270084e+00 4.20743513e-01]]

### Pivot Table

In [22]:
#Determine pivot table
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                       "bar", "bar", "bar", "bar"],
                    "B": ["one", "one", "one", "two", "two",
                          "one", "one", "two", "two"],
                    "C": ["small", "large", "large", "small",
                          "small", "large", "small", "small",
                          "large"],
                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

In [23]:
df.head(9)

     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [24]:
###################################想办法生成以下表格，行为A、B，列为C###################################
table = pivot_table(df, values='D', index=['A', 'B'],
                  columns=['C'], aggfunc=np.sum)

###################################想办法生成以下表格，行为A、B，列为C###################################
table

C        large  small
A   B
bar one    4.0    5.0
    two    7.0    6.0
foo one    4.0    1.0
    two    NaN    6.0

### Merging dataframes

In [25]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                       index=[0, 1, 2, 3])
    

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                       index=[4, 5, 6, 7])
    

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                       'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                       index=[8, 9, 10, 11])
    
###################################将df1,df2,df3按行拼接到一起，并赋给result###################################
frames = [df1, df2, df3]

result = pd.concat(frames)

###################################将df1,df2,df3按行拼接到一起，并赋给result####################################

print(result)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11